// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/de/v1/genesis.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Params } from "./params";
import { FeeGrant, OperatorAuthorization, VSOperatorAuthorization } from "./types";

export const protobufPackage = "verana.de.v1";

/** GenesisState defines the de module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params:
    | Params
    | undefined;
  /** operator_authorizations is a list of all OperatorAuthorization objects */
  operatorAuthorizations: OperatorAuthorization[];
  /** fee_grants is a list of all FeeGrant objects */
  feeGrants: FeeGrant[];
  /** vs_operator_authorizations is a list of all VSOperatorAuthorization objects */
  vsOperatorAuthorizations: VSOperatorAuthorization[];
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, operatorAuthorizations: [], feeGrants: [], vsOperatorAuthorizations: [] };
}

export const GenesisState = {
  encode(message: GenesisState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.operatorAuthorizations) {
      OperatorAuthorization.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    for (const v of message.feeGrants) {
      FeeGrant.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    for (const v of message.vsOperatorAuthorizations) {
      VSOperatorAuthorization.encode(v!, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.operatorAuthorizations.push(OperatorAuthorization.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.feeGrants.push(FeeGrant.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.vsOperatorAuthorizations.push(VSOperatorAuthorization.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      operatorAuthorizations: globalThis.Array.isArray(object?.operatorAuthorizations)
        ? object.operatorAuthorizations.map((e: any) => OperatorAuthorization.fromJSON(e))
        : [],
      feeGrants: globalThis.Array.isArray(object?.feeGrants)
        ? object.feeGrants.map((e: any) => FeeGrant.fromJSON(e))
        : [],
      vsOperatorAuthorizations: globalThis.Array.isArray(object?.vsOperatorAuthorizations)
        ? object.vsOperatorAuthorizations.map((e: any) => VSOperatorAuthorization.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.operatorAuthorizations?.length) {
      obj.operatorAuthorizations = message.operatorAuthorizations.map((e) => OperatorAuthorization.toJSON(e));
    }
    if (message.feeGrants?.length) {
      obj.feeGrants = message.feeGrants.map((e) => FeeGrant.toJSON(e));
    }
    if (message.vsOperatorAuthorizations?.length) {
      obj.vsOperatorAuthorizations = message.vsOperatorAuthorizations.map((e) => VSOperatorAuthorization.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.operatorAuthorizations = object.operatorAuthorizations?.map((e) => OperatorAuthorization.fromPartial(e)) ||
      [];
    message.feeGrants = object.feeGrants?.map((e) => FeeGrant.fromPartial(e)) || [];
    message.vsOperatorAuthorizations =
      object.vsOperatorAuthorizations?.map((e) => VSOperatorAuthorization.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
