// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/tr/v1/params.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "verana.tr.v1";

/** Params defines the parameters for the module. */
export interface Params {
  trustRegistryTrustDeposit: Long;
  trustUnitPrice: Long;
}

function createBaseParams(): Params {
  return { trustRegistryTrustDeposit: Long.UZERO, trustUnitPrice: Long.UZERO };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (!message.trustRegistryTrustDeposit.equals(Long.UZERO)) {
      writer.uint32(8).uint64(message.trustRegistryTrustDeposit);
    }
    if (!message.trustUnitPrice.equals(Long.UZERO)) {
      writer.uint32(16).uint64(message.trustUnitPrice);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.trustRegistryTrustDeposit = reader.uint64() as Long;
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.trustUnitPrice = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      trustRegistryTrustDeposit: isSet(object.trustRegistryTrustDeposit)
        ? Long.fromValue(object.trustRegistryTrustDeposit)
        : Long.UZERO,
      trustUnitPrice: isSet(object.trustUnitPrice) ? Long.fromValue(object.trustUnitPrice) : Long.UZERO,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (!message.trustRegistryTrustDeposit.equals(Long.UZERO)) {
      obj.trustRegistryTrustDeposit = (message.trustRegistryTrustDeposit || Long.UZERO).toString();
    }
    if (!message.trustUnitPrice.equals(Long.UZERO)) {
      obj.trustUnitPrice = (message.trustUnitPrice || Long.UZERO).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.trustRegistryTrustDeposit =
      (object.trustRegistryTrustDeposit !== undefined && object.trustRegistryTrustDeposit !== null)
        ? Long.fromValue(object.trustRegistryTrustDeposit)
        : Long.UZERO;
    message.trustUnitPrice = (object.trustUnitPrice !== undefined && object.trustUnitPrice !== null)
      ? Long.fromValue(object.trustUnitPrice)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
