// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: verana/de/v1/tx.proto

package dev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_UpdateParams_FullMethodName                = "/verana.de.v1.Msg/UpdateParams"
	Msg_GrantOperatorAuthorization_FullMethodName  = "/verana.de.v1.Msg/GrantOperatorAuthorization"
	Msg_RevokeOperatorAuthorization_FullMethodName = "/verana.de.v1.Msg/RevokeOperatorAuthorization"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the Msg service.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// [MOD-DE-MSG-3] Grant Operator Authorization
	GrantOperatorAuthorization(ctx context.Context, in *MsgGrantOperatorAuthorization, opts ...grpc.CallOption) (*MsgGrantOperatorAuthorizationResponse, error)
	// [MOD-DE-MSG-4] Revoke Operator Authorization
	RevokeOperatorAuthorization(ctx context.Context, in *MsgRevokeOperatorAuthorization, opts ...grpc.CallOption) (*MsgRevokeOperatorAuthorizationResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GrantOperatorAuthorization(ctx context.Context, in *MsgGrantOperatorAuthorization, opts ...grpc.CallOption) (*MsgGrantOperatorAuthorizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgGrantOperatorAuthorizationResponse)
	err := c.cc.Invoke(ctx, Msg_GrantOperatorAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeOperatorAuthorization(ctx context.Context, in *MsgRevokeOperatorAuthorization, opts ...grpc.CallOption) (*MsgRevokeOperatorAuthorizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRevokeOperatorAuthorizationResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeOperatorAuthorization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// [MOD-DE-MSG-3] Grant Operator Authorization
	GrantOperatorAuthorization(context.Context, *MsgGrantOperatorAuthorization) (*MsgGrantOperatorAuthorizationResponse, error)
	// [MOD-DE-MSG-4] Revoke Operator Authorization
	RevokeOperatorAuthorization(context.Context, *MsgRevokeOperatorAuthorization) (*MsgRevokeOperatorAuthorizationResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) GrantOperatorAuthorization(context.Context, *MsgGrantOperatorAuthorization) (*MsgGrantOperatorAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantOperatorAuthorization not implemented")
}
func (UnimplementedMsgServer) RevokeOperatorAuthorization(context.Context, *MsgRevokeOperatorAuthorization) (*MsgRevokeOperatorAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeOperatorAuthorization not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GrantOperatorAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGrantOperatorAuthorization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GrantOperatorAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GrantOperatorAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GrantOperatorAuthorization(ctx, req.(*MsgGrantOperatorAuthorization))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeOperatorAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeOperatorAuthorization)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeOperatorAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeOperatorAuthorization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeOperatorAuthorization(ctx, req.(*MsgRevokeOperatorAuthorization))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verana.de.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "GrantOperatorAuthorization",
			Handler:    _Msg_GrantOperatorAuthorization_Handler,
		},
		{
			MethodName: "RevokeOperatorAuthorization",
			Handler:    _Msg_RevokeOperatorAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verana/de/v1/tx.proto",
}
