// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/td/v1/genesis.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Params } from "./params";

export const protobufPackage = "verana.td.v1";

/** GenesisState defines the trustdeposit module's genesis state. */
export interface GenesisState {
  /** params defines all the parameters of the module. */
  params?: Params | undefined;
  trustDeposits: TrustDepositRecord[];
}

/** TrustDepositRecord defines a trust deposit entry for genesis state */
export interface TrustDepositRecord {
  account: string;
  share: string;
  amount: Long;
  claimable: Long;
}

function createBaseGenesisState(): GenesisState {
  return { params: undefined, trustDeposits: [] };
}

export const GenesisState = {
  encode(message: GenesisState, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).ldelim();
    }
    for (const v of message.trustDeposits) {
      TrustDepositRecord.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.trustDeposits.push(TrustDepositRecord.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
      trustDeposits: globalThis.Array.isArray(object?.trustDeposits)
        ? object.trustDeposits.map((e: any) => TrustDepositRecord.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    if (message.trustDeposits?.length) {
      obj.trustDeposits = message.trustDeposits.map((e) => TrustDepositRecord.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    message.trustDeposits = object.trustDeposits?.map((e) => TrustDepositRecord.fromPartial(e)) || [];
    return message;
  },
};

function createBaseTrustDepositRecord(): TrustDepositRecord {
  return { account: "", share: "", amount: Long.UZERO, claimable: Long.UZERO };
}

export const TrustDepositRecord = {
  encode(message: TrustDepositRecord, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    if (message.share !== "") {
      writer.uint32(18).string(message.share);
    }
    if (!message.amount.equals(Long.UZERO)) {
      writer.uint32(24).uint64(message.amount);
    }
    if (!message.claimable.equals(Long.UZERO)) {
      writer.uint32(32).uint64(message.claimable);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): TrustDepositRecord {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrustDepositRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.share = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.amount = reader.uint64() as Long;
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.claimable = reader.uint64() as Long;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrustDepositRecord {
    return {
      account: isSet(object.account) ? globalThis.String(object.account) : "",
      share: isSet(object.share) ? globalThis.String(object.share) : "",
      amount: isSet(object.amount) ? Long.fromValue(object.amount) : Long.UZERO,
      claimable: isSet(object.claimable) ? Long.fromValue(object.claimable) : Long.UZERO,
    };
  },

  toJSON(message: TrustDepositRecord): unknown {
    const obj: any = {};
    if (message.account !== "") {
      obj.account = message.account;
    }
    if (message.share !== "") {
      obj.share = message.share;
    }
    if (!message.amount.equals(Long.UZERO)) {
      obj.amount = (message.amount || Long.UZERO).toString();
    }
    if (!message.claimable.equals(Long.UZERO)) {
      obj.claimable = (message.claimable || Long.UZERO).toString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrustDepositRecord>, I>>(base?: I): TrustDepositRecord {
    return TrustDepositRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrustDepositRecord>, I>>(object: I): TrustDepositRecord {
    const message = createBaseTrustDepositRecord();
    message.account = object.account ?? "";
    message.share = object.share ?? "";
    message.amount = (object.amount !== undefined && object.amount !== null)
      ? Long.fromValue(object.amount)
      : Long.UZERO;
    message.claimable = (object.claimable !== undefined && object.claimable !== null)
      ? Long.fromValue(object.claimable)
      : Long.UZERO;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
