// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verana/ec/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgCreateEcosystem implements MOD-ES-MSG-1. Signed by `operator`;
// AUTHZ-CHECK-5 resolves the signing `corporation` policy_address to the
// controlling Corporation entry. Seeds v1 of the Ecosystem's Governance
// Framework via MOD-GF.
type MsgCreateEcosystem struct {
	Corporation  string `protobuf:"bytes,1,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Operator     string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Did          string `protobuf:"bytes,3,opt,name=did,proto3" json:"did,omitempty"`
	Language     string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	DocUrl       string `protobuf:"bytes,5,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	DocDigestSri string `protobuf:"bytes,6,opt,name=doc_digest_sri,json=docDigestSri,proto3" json:"doc_digest_sri,omitempty"`
}

func (m *MsgCreateEcosystem) Reset()         { *m = MsgCreateEcosystem{} }
func (m *MsgCreateEcosystem) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEcosystem) ProtoMessage()    {}
func (*MsgCreateEcosystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{2}
}
func (m *MsgCreateEcosystem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEcosystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEcosystem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEcosystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEcosystem.Merge(m, src)
}
func (m *MsgCreateEcosystem) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEcosystem) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEcosystem.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEcosystem proto.InternalMessageInfo

func (m *MsgCreateEcosystem) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *MsgCreateEcosystem) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgCreateEcosystem) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *MsgCreateEcosystem) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *MsgCreateEcosystem) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *MsgCreateEcosystem) GetDocDigestSri() string {
	if m != nil {
		return m.DocDigestSri
	}
	return ""
}

type MsgCreateEcosystemResponse struct {
	EcosystemId uint64 `protobuf:"varint,1,opt,name=ecosystem_id,json=ecosystemId,proto3" json:"ecosystem_id,omitempty"`
}

func (m *MsgCreateEcosystemResponse) Reset()         { *m = MsgCreateEcosystemResponse{} }
func (m *MsgCreateEcosystemResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateEcosystemResponse) ProtoMessage()    {}
func (*MsgCreateEcosystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{3}
}
func (m *MsgCreateEcosystemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateEcosystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateEcosystemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateEcosystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateEcosystemResponse.Merge(m, src)
}
func (m *MsgCreateEcosystemResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateEcosystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateEcosystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateEcosystemResponse proto.InternalMessageInfo

func (m *MsgCreateEcosystemResponse) GetEcosystemId() uint64 {
	if m != nil {
		return m.EcosystemId
	}
	return 0
}

// MsgUpdateEcosystem implements MOD-ES-MSG-2. Only `did` is mutable.
type MsgUpdateEcosystem struct {
	Corporation string `protobuf:"bytes,1,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Operator    string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Id          uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Did         string `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *MsgUpdateEcosystem) Reset()         { *m = MsgUpdateEcosystem{} }
func (m *MsgUpdateEcosystem) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEcosystem) ProtoMessage()    {}
func (*MsgUpdateEcosystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{4}
}
func (m *MsgUpdateEcosystem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEcosystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEcosystem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEcosystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEcosystem.Merge(m, src)
}
func (m *MsgUpdateEcosystem) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEcosystem) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEcosystem.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEcosystem proto.InternalMessageInfo

func (m *MsgUpdateEcosystem) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *MsgUpdateEcosystem) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateEcosystem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateEcosystem) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type MsgUpdateEcosystemResponse struct {
}

func (m *MsgUpdateEcosystemResponse) Reset()         { *m = MsgUpdateEcosystemResponse{} }
func (m *MsgUpdateEcosystemResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateEcosystemResponse) ProtoMessage()    {}
func (*MsgUpdateEcosystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{5}
}
func (m *MsgUpdateEcosystemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateEcosystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateEcosystemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateEcosystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateEcosystemResponse.Merge(m, src)
}
func (m *MsgUpdateEcosystemResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateEcosystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateEcosystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateEcosystemResponse proto.InternalMessageInfo

// MsgArchiveEcosystem implements MOD-ES-MSG-3. `archive` is a boolean toggle;
// submitting the current state is an idempotency abort.
type MsgArchiveEcosystem struct {
	Corporation string `protobuf:"bytes,1,opt,name=corporation,proto3" json:"corporation,omitempty"`
	Operator    string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Id          uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Archive     bool   `protobuf:"varint,4,opt,name=archive,proto3" json:"archive,omitempty"`
}

func (m *MsgArchiveEcosystem) Reset()         { *m = MsgArchiveEcosystem{} }
func (m *MsgArchiveEcosystem) String() string { return proto.CompactTextString(m) }
func (*MsgArchiveEcosystem) ProtoMessage()    {}
func (*MsgArchiveEcosystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{6}
}
func (m *MsgArchiveEcosystem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgArchiveEcosystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgArchiveEcosystem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgArchiveEcosystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgArchiveEcosystem.Merge(m, src)
}
func (m *MsgArchiveEcosystem) XXX_Size() int {
	return m.Size()
}
func (m *MsgArchiveEcosystem) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgArchiveEcosystem.DiscardUnknown(m)
}

var xxx_messageInfo_MsgArchiveEcosystem proto.InternalMessageInfo

func (m *MsgArchiveEcosystem) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *MsgArchiveEcosystem) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgArchiveEcosystem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgArchiveEcosystem) GetArchive() bool {
	if m != nil {
		return m.Archive
	}
	return false
}

type MsgArchiveEcosystemResponse struct {
}

func (m *MsgArchiveEcosystemResponse) Reset()         { *m = MsgArchiveEcosystemResponse{} }
func (m *MsgArchiveEcosystemResponse) String() string { return proto.CompactTextString(m) }
func (*MsgArchiveEcosystemResponse) ProtoMessage()    {}
func (*MsgArchiveEcosystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_271e0a0e95dc4c75, []int{7}
}
func (m *MsgArchiveEcosystemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgArchiveEcosystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgArchiveEcosystemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgArchiveEcosystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgArchiveEcosystemResponse.Merge(m, src)
}
func (m *MsgArchiveEcosystemResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgArchiveEcosystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgArchiveEcosystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgArchiveEcosystemResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "verana.ec.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "verana.ec.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateEcosystem)(nil), "verana.ec.v1.MsgCreateEcosystem")
	proto.RegisterType((*MsgCreateEcosystemResponse)(nil), "verana.ec.v1.MsgCreateEcosystemResponse")
	proto.RegisterType((*MsgUpdateEcosystem)(nil), "verana.ec.v1.MsgUpdateEcosystem")
	proto.RegisterType((*MsgUpdateEcosystemResponse)(nil), "verana.ec.v1.MsgUpdateEcosystemResponse")
	proto.RegisterType((*MsgArchiveEcosystem)(nil), "verana.ec.v1.MsgArchiveEcosystem")
	proto.RegisterType((*MsgArchiveEcosystemResponse)(nil), "verana.ec.v1.MsgArchiveEcosystemResponse")
}

func init() { proto.RegisterFile("verana/ec/v1/tx.proto", fileDescriptor_271e0a0e95dc4c75) }

var fileDescriptor_271e0a0e95dc4c75 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x4d, 0x4b, 0x1c, 0x4b,
	0x14, 0x9d, 0x9e, 0x19, 0x47, 0x2d, 0x07, 0xf5, 0xd5, 0xf3, 0x61, 0xdb, 0x3e, 0xdb, 0xb1, 0x79,
	0x0f, 0x8c, 0x60, 0x77, 0x34, 0x21, 0x81, 0xd9, 0x04, 0x4d, 0x42, 0xc8, 0x62, 0x20, 0xb4, 0x71,
	0x13, 0x08, 0x93, 0xb2, 0xab, 0x28, 0x1b, 0xa6, 0xbb, 0x9a, 0xaa, 0x9a, 0x41, 0x77, 0xc1, 0x65,
	0x56, 0xf9, 0x13, 0x81, 0x2c, 0x25, 0xe4, 0x47, 0xb8, 0x94, 0xac, 0x42, 0x16, 0x21, 0x68, 0xc0,
	0xbf, 0x11, 0xba, 0xfa, 0x43, 0xad, 0x89, 0x9a, 0x5d, 0xb2, 0x19, 0xaa, 0xce, 0x39, 0xf7, 0xd6,
	0xbd, 0xa7, 0x6f, 0xd5, 0x80, 0x7f, 0x06, 0x84, 0xa3, 0x18, 0x79, 0x24, 0xf0, 0x06, 0x6b, 0x9e,
	0xdc, 0x73, 0x13, 0xce, 0x24, 0x83, 0xcd, 0x0c, 0x76, 0x49, 0xe0, 0x0e, 0xd6, 0xac, 0xbf, 0x50,
	0x14, 0xc6, 0xcc, 0x53, 0xbf, 0x99, 0xc0, 0x9a, 0x0d, 0x98, 0x88, 0x98, 0xf0, 0x22, 0x41, 0xd3,
	0xc0, 0x48, 0xd0, 0x9c, 0x98, 0xcb, 0x88, 0xae, 0xda, 0x79, 0xd9, 0x26, 0xa7, 0x66, 0x28, 0xa3,
	0x2c, 0xc3, 0xd3, 0x55, 0x11, 0x70, 0xa9, 0x82, 0x04, 0x71, 0x14, 0xe5, 0x01, 0xce, 0x07, 0x03,
	0x4c, 0x75, 0x04, 0xdd, 0x4e, 0x30, 0x92, 0xe4, 0x99, 0x62, 0xe0, 0x3d, 0x30, 0x8e, 0xfa, 0x72,
	0x97, 0xf1, 0x50, 0xee, 0x9b, 0x46, 0xcb, 0x58, 0x1e, 0xdf, 0x34, 0x3f, 0x7d, 0x5c, 0x9d, 0xc9,
	0x4f, 0xda, 0xc0, 0x98, 0x13, 0x21, 0xb6, 0x24, 0x0f, 0x63, 0xea, 0x9f, 0x4b, 0xe1, 0x7d, 0xd0,
	0xc8, 0x72, 0x9b, 0xd5, 0x96, 0xb1, 0x3c, 0xb1, 0x3e, 0xe3, 0x5e, 0x6c, 0xd1, 0xcd, 0xb2, 0x6f,
	0x8e, 0x1f, 0x7d, 0x5d, 0xac, 0xbc, 0x3f, 0x3b, 0x5c, 0x31, 0xfc, 0x5c, 0xde, 0x76, 0x0f, 0xce,
	0x0e, 0x57, 0xce, 0x13, 0xbd, 0x39, 0x3b, 0x5c, 0x99, 0xcf, 0x4b, 0xde, 0x4b, 0x8b, 0xd6, 0x0a,
	0x74, 0xe6, 0xc0, 0xac, 0x06, 0xf9, 0x44, 0x24, 0x2c, 0x16, 0xc4, 0x79, 0x57, 0x05, 0xb0, 0x23,
	0xe8, 0x43, 0x4e, 0x90, 0x24, 0x8f, 0x03, 0x26, 0xf6, 0x85, 0x24, 0x11, 0x6c, 0x83, 0x89, 0x80,
	0xf1, 0x84, 0x71, 0x24, 0x43, 0x16, 0xdf, 0xd8, 0xd4, 0x45, 0x31, 0xbc, 0x0b, 0xc6, 0x58, 0x42,
	0x38, 0x92, 0x8c, 0xab, 0xc6, 0xae, 0x0b, 0x2c, 0x95, 0x70, 0x1a, 0xd4, 0x70, 0x88, 0xcd, 0x5a,
	0x1a, 0xe0, 0xa7, 0x4b, 0x68, 0x81, 0xb1, 0x1e, 0x8a, 0x69, 0x1f, 0x51, 0x62, 0xd6, 0x15, 0x5c,
	0xee, 0xe1, 0x2c, 0x18, 0xc5, 0x2c, 0xe8, 0xf6, 0x79, 0xcf, 0x1c, 0x51, 0x54, 0x03, 0xb3, 0x60,
	0x9b, 0xf7, 0xe0, 0x7f, 0x60, 0x32, 0x25, 0x70, 0x48, 0x89, 0x90, 0x5d, 0xc1, 0x43, 0xb3, 0xa1,
	0xf8, 0x26, 0x66, 0xc1, 0x23, 0x05, 0x6e, 0xf1, 0xb0, 0x7d, 0x3b, 0x35, 0xb0, 0x3c, 0x3b, 0xf5,
	0xcf, 0xd6, 0xfc, 0xd3, 0x0c, 0x71, 0x1e, 0x00, 0x6b, 0x18, 0x2d, 0x5c, 0x84, 0x4b, 0xa0, 0x49,
	0x0a, 0xb0, 0x1b, 0x62, 0xe5, 0x57, 0xdd, 0x9f, 0x28, 0xb1, 0xa7, 0xd8, 0xf9, 0x62, 0x28, 0xa3,
	0xb3, 0x8f, 0xf0, 0x3b, 0x8d, 0x9e, 0x04, 0xd5, 0xdc, 0xe7, 0xba, 0x5f, 0x0d, 0x71, 0x61, 0x7c,
	0xbd, 0x34, 0xfe, 0x17, 0xdc, 0xd1, 0xba, 0x70, 0xfe, 0x55, 0xee, 0x68, 0x68, 0x39, 0x63, 0xdf,
	0x0d, 0xf0, 0x77, 0x47, 0xd0, 0x0d, 0x1e, 0xec, 0x86, 0x83, 0x3f, 0xaa, 0x77, 0x13, 0x8c, 0xa2,
	0xac, 0x2a, 0xd5, 0xff, 0x98, 0x5f, 0x6c, 0xdb, 0x6b, 0x43, 0x1e, 0x2c, 0x6a, 0x1e, 0xe8, 0xed,
	0x38, 0x0b, 0x60, 0xfe, 0x27, 0x70, 0xe1, 0xc2, 0xfa, 0x41, 0x0d, 0xd4, 0x3a, 0x82, 0xc2, 0xe7,
	0xa0, 0x79, 0xe9, 0xf5, 0x58, 0xb8, 0x7c, 0xeb, 0xb5, 0x8b, 0x6a, 0xfd, 0x7f, 0x2d, 0x5d, 0x4e,
	0xe0, 0x4b, 0x30, 0xa5, 0xdf, 0xe1, 0xd6, 0x50, 0xa4, 0xa6, 0xb0, 0x96, 0x6f, 0x52, 0x5c, 0x4c,
	0xaf, 0x4f, 0x6e, 0xeb, 0x8a, 0xc2, 0xae, 0x4b, 0x7f, 0xc5, 0x84, 0xc0, 0x57, 0x60, 0x7a, 0x68,
	0x3a, 0x96, 0x86, 0xa2, 0x75, 0x89, 0x75, 0xeb, 0x46, 0x49, 0x71, 0x82, 0x35, 0xf2, 0x3a, 0x7d,
	0x41, 0x37, 0x9f, 0x1c, 0x9d, 0xd8, 0xc6, 0xf1, 0x89, 0x6d, 0x7c, 0x3b, 0xb1, 0x8d, 0xb7, 0xa7,
	0x76, 0xe5, 0xf8, 0xd4, 0xae, 0x7c, 0x3e, 0xb5, 0x2b, 0x2f, 0x56, 0x69, 0x28, 0x77, 0xfb, 0x3b,
	0x6e, 0xc0, 0x22, 0x2f, 0xcb, 0xba, 0xda, 0x43, 0x3b, 0xa2, 0x58, 0xc7, 0x0c, 0x93, 0xec, 0xd3,
	0xcb, 0xfd, 0x84, 0x88, 0x9d, 0x86, 0xfa, 0x3b, 0xb8, 0xf3, 0x23, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x51, 0x74, 0x78, 0xad, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// [MOD-ES-MSG-1] Create New Ecosystem.
	CreateEcosystem(ctx context.Context, in *MsgCreateEcosystem, opts ...grpc.CallOption) (*MsgCreateEcosystemResponse, error)
	// [MOD-ES-MSG-2] Update Ecosystem (rotate did).
	UpdateEcosystem(ctx context.Context, in *MsgUpdateEcosystem, opts ...grpc.CallOption) (*MsgUpdateEcosystemResponse, error)
	// [MOD-ES-MSG-3] Archive/unarchive Ecosystem.
	ArchiveEcosystem(ctx context.Context, in *MsgArchiveEcosystem, opts ...grpc.CallOption) (*MsgArchiveEcosystemResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/verana.ec.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateEcosystem(ctx context.Context, in *MsgCreateEcosystem, opts ...grpc.CallOption) (*MsgCreateEcosystemResponse, error) {
	out := new(MsgCreateEcosystemResponse)
	err := c.cc.Invoke(ctx, "/verana.ec.v1.Msg/CreateEcosystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateEcosystem(ctx context.Context, in *MsgUpdateEcosystem, opts ...grpc.CallOption) (*MsgUpdateEcosystemResponse, error) {
	out := new(MsgUpdateEcosystemResponse)
	err := c.cc.Invoke(ctx, "/verana.ec.v1.Msg/UpdateEcosystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ArchiveEcosystem(ctx context.Context, in *MsgArchiveEcosystem, opts ...grpc.CallOption) (*MsgArchiveEcosystemResponse, error) {
	out := new(MsgArchiveEcosystemResponse)
	err := c.cc.Invoke(ctx, "/verana.ec.v1.Msg/ArchiveEcosystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// [MOD-ES-MSG-1] Create New Ecosystem.
	CreateEcosystem(context.Context, *MsgCreateEcosystem) (*MsgCreateEcosystemResponse, error)
	// [MOD-ES-MSG-2] Update Ecosystem (rotate did).
	UpdateEcosystem(context.Context, *MsgUpdateEcosystem) (*MsgUpdateEcosystemResponse, error)
	// [MOD-ES-MSG-3] Archive/unarchive Ecosystem.
	ArchiveEcosystem(context.Context, *MsgArchiveEcosystem) (*MsgArchiveEcosystemResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateEcosystem(ctx context.Context, req *MsgCreateEcosystem) (*MsgCreateEcosystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEcosystem not implemented")
}
func (*UnimplementedMsgServer) UpdateEcosystem(ctx context.Context, req *MsgUpdateEcosystem) (*MsgUpdateEcosystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEcosystem not implemented")
}
func (*UnimplementedMsgServer) ArchiveEcosystem(ctx context.Context, req *MsgArchiveEcosystem) (*MsgArchiveEcosystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveEcosystem not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.ec.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateEcosystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateEcosystem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateEcosystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.ec.v1.Msg/CreateEcosystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateEcosystem(ctx, req.(*MsgCreateEcosystem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateEcosystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateEcosystem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateEcosystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.ec.v1.Msg/UpdateEcosystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateEcosystem(ctx, req.(*MsgUpdateEcosystem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ArchiveEcosystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgArchiveEcosystem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ArchiveEcosystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.ec.v1.Msg/ArchiveEcosystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ArchiveEcosystem(ctx, req.(*MsgArchiveEcosystem))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verana.ec.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateEcosystem",
			Handler:    _Msg_CreateEcosystem_Handler,
		},
		{
			MethodName: "UpdateEcosystem",
			Handler:    _Msg_UpdateEcosystem_Handler,
		},
		{
			MethodName: "ArchiveEcosystem",
			Handler:    _Msg_ArchiveEcosystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verana/ec/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateEcosystem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEcosystem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEcosystem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DocDigestSri) > 0 {
		i -= len(m.DocDigestSri)
		copy(dAtA[i:], m.DocDigestSri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocDigestSri)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DocUrl) > 0 {
		i -= len(m.DocUrl)
		copy(dAtA[i:], m.DocUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Language) > 0 {
		i -= len(m.Language)
		copy(dAtA[i:], m.Language)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Language)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Corporation) > 0 {
		i -= len(m.Corporation)
		copy(dAtA[i:], m.Corporation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Corporation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateEcosystemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateEcosystemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateEcosystemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EcosystemId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EcosystemId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEcosystem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEcosystem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEcosystem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x22
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Corporation) > 0 {
		i -= len(m.Corporation)
		copy(dAtA[i:], m.Corporation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Corporation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateEcosystemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateEcosystemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateEcosystemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgArchiveEcosystem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgArchiveEcosystem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgArchiveEcosystem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Archive {
		i--
		if m.Archive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Corporation) > 0 {
		i -= len(m.Corporation)
		copy(dAtA[i:], m.Corporation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Corporation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgArchiveEcosystemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgArchiveEcosystemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgArchiveEcosystemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateEcosystem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Corporation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Language)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocDigestSri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateEcosystemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EcosystemId != 0 {
		n += 1 + sovTx(uint64(m.EcosystemId))
	}
	return n
}

func (m *MsgUpdateEcosystem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Corporation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateEcosystemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgArchiveEcosystem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Corporation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.Archive {
		n += 2
	}
	return n
}

func (m *MsgArchiveEcosystemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateEcosystem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEcosystem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEcosystem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corporation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Corporation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocDigestSri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocDigestSri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateEcosystemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateEcosystemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateEcosystemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcosystemId", wireType)
			}
			m.EcosystemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EcosystemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEcosystem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEcosystem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEcosystem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corporation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Corporation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateEcosystemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateEcosystemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateEcosystemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgArchiveEcosystem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgArchiveEcosystem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgArchiveEcosystem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corporation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Corporation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgArchiveEcosystemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgArchiveEcosystemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgArchiveEcosystemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
