// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verana/gf/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// [MOD-GF-MSG-1] Adds (or replaces) a GovernanceFrameworkDocument for a draft
// version owned by an Ecosystem or a Corporation.
type MsgAddGovernanceFrameworkDocument struct {
	// corporation is the signing corporation (group_policy_address).
	Corporation string `protobuf:"bytes,1,opt,name=corporation,proto3" json:"corporation,omitempty"`
	// operator is the account authorized by corporation to run this Msg.
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// ecosystem_id is optional. If set, the GF target is an Ecosystem owned by
	// `corporation`. If zero, the GF target is the signing Corporation's own CGF.
	EcosystemId uint64 `protobuf:"varint,3,opt,name=ecosystem_id,json=ecosystemId,proto3" json:"ecosystem_id,omitempty"`
	// doc_language is a BCP 47 language tag.
	DocLanguage string `protobuf:"bytes,4,opt,name=doc_language,json=docLanguage,proto3" json:"doc_language,omitempty"`
	// doc_url is the URL where the document is published.
	DocUrl string `protobuf:"bytes,5,opt,name=doc_url,json=docUrl,proto3" json:"doc_url,omitempty"`
	// doc_digest_sri is the SRI digest of the document.
	DocDigestSri string `protobuf:"bytes,6,opt,name=doc_digest_sri,json=docDigestSri,proto3" json:"doc_digest_sri,omitempty"`
	// version is the target governance framework version.
	Version uint32 `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
}

func (m *MsgAddGovernanceFrameworkDocument) Reset()         { *m = MsgAddGovernanceFrameworkDocument{} }
func (m *MsgAddGovernanceFrameworkDocument) String() string { return proto.CompactTextString(m) }
func (*MsgAddGovernanceFrameworkDocument) ProtoMessage()    {}
func (*MsgAddGovernanceFrameworkDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{2}
}
func (m *MsgAddGovernanceFrameworkDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddGovernanceFrameworkDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddGovernanceFrameworkDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddGovernanceFrameworkDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddGovernanceFrameworkDocument.Merge(m, src)
}
func (m *MsgAddGovernanceFrameworkDocument) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddGovernanceFrameworkDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddGovernanceFrameworkDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddGovernanceFrameworkDocument proto.InternalMessageInfo

func (m *MsgAddGovernanceFrameworkDocument) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *MsgAddGovernanceFrameworkDocument) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgAddGovernanceFrameworkDocument) GetEcosystemId() uint64 {
	if m != nil {
		return m.EcosystemId
	}
	return 0
}

func (m *MsgAddGovernanceFrameworkDocument) GetDocLanguage() string {
	if m != nil {
		return m.DocLanguage
	}
	return ""
}

func (m *MsgAddGovernanceFrameworkDocument) GetDocUrl() string {
	if m != nil {
		return m.DocUrl
	}
	return ""
}

func (m *MsgAddGovernanceFrameworkDocument) GetDocDigestSri() string {
	if m != nil {
		return m.DocDigestSri
	}
	return ""
}

func (m *MsgAddGovernanceFrameworkDocument) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type MsgAddGovernanceFrameworkDocumentResponse struct {
}

func (m *MsgAddGovernanceFrameworkDocumentResponse) Reset() {
	*m = MsgAddGovernanceFrameworkDocumentResponse{}
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgAddGovernanceFrameworkDocumentResponse) ProtoMessage() {}
func (*MsgAddGovernanceFrameworkDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{3}
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddGovernanceFrameworkDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddGovernanceFrameworkDocumentResponse.Merge(m, src)
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddGovernanceFrameworkDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddGovernanceFrameworkDocumentResponse proto.InternalMessageInfo

// [MOD-GF-MSG-2] Activates the next governance framework version for an
// Ecosystem or Corporation owned by the signing corporation.
type MsgIncreaseActiveGovernanceFrameworkVersion struct {
	// corporation is the signing corporation (group_policy_address).
	Corporation string `protobuf:"bytes,1,opt,name=corporation,proto3" json:"corporation,omitempty"`
	// operator is the account authorized by corporation to run this Msg.
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// ecosystem_id is optional. If set, target is the Ecosystem; otherwise the
	// signing Corporation's own CGF.
	EcosystemId uint64 `protobuf:"varint,3,opt,name=ecosystem_id,json=ecosystemId,proto3" json:"ecosystem_id,omitempty"`
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) Reset() {
	*m = MsgIncreaseActiveGovernanceFrameworkVersion{}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) String() string {
	return proto.CompactTextString(m)
}
func (*MsgIncreaseActiveGovernanceFrameworkVersion) ProtoMessage() {}
func (*MsgIncreaseActiveGovernanceFrameworkVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{4}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersion.Merge(m, src)
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) XXX_Size() int {
	return m.Size()
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersion.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersion proto.InternalMessageInfo

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) GetCorporation() string {
	if m != nil {
		return m.Corporation
	}
	return ""
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) GetEcosystemId() uint64 {
	if m != nil {
		return m.EcosystemId
	}
	return 0
}

type MsgIncreaseActiveGovernanceFrameworkVersionResponse struct {
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) Reset() {
	*m = MsgIncreaseActiveGovernanceFrameworkVersionResponse{}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) String() string {
	return proto.CompactTextString(m)
}
func (*MsgIncreaseActiveGovernanceFrameworkVersionResponse) ProtoMessage() {}
func (*MsgIncreaseActiveGovernanceFrameworkVersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c91e7c6576fbd22a, []int{5}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersionResponse.Merge(m, src)
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIncreaseActiveGovernanceFrameworkVersionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "verana.gf.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "verana.gf.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgAddGovernanceFrameworkDocument)(nil), "verana.gf.v1.MsgAddGovernanceFrameworkDocument")
	proto.RegisterType((*MsgAddGovernanceFrameworkDocumentResponse)(nil), "verana.gf.v1.MsgAddGovernanceFrameworkDocumentResponse")
	proto.RegisterType((*MsgIncreaseActiveGovernanceFrameworkVersion)(nil), "verana.gf.v1.MsgIncreaseActiveGovernanceFrameworkVersion")
	proto.RegisterType((*MsgIncreaseActiveGovernanceFrameworkVersionResponse)(nil), "verana.gf.v1.MsgIncreaseActiveGovernanceFrameworkVersionResponse")
}

func init() { proto.RegisterFile("verana/gf/v1/tx.proto", fileDescriptor_c91e7c6576fbd22a) }

var fileDescriptor_c91e7c6576fbd22a = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xf4, 0x47, 0x6a, 0x27, 0x55, 0x71, 0xa9, 0x74, 0xbb, 0xe2, 0x9a, 0x06, 0x85, 0xb5,
	0xa5, 0xbb, 0xb4, 0x55, 0x8b, 0xb9, 0x48, 0x42, 0x51, 0x0a, 0x06, 0x64, 0x6b, 0x3d, 0x78, 0x09,
	0xd3, 0xdd, 0xe9, 0x74, 0x31, 0xbb, 0xb3, 0xcc, 0x4c, 0xd6, 0xf6, 0x26, 0x1e, 0x0b, 0x82, 0x67,
	0xff, 0x82, 0x1e, 0x83, 0xf8, 0x47, 0xf4, 0x58, 0x3c, 0x79, 0x12, 0x49, 0x0e, 0xf9, 0x0b, 0xbc,
	0xcb, 0xec, 0x6e, 0xd2, 0xfc, 0x90, 0x24, 0xf5, 0xe4, 0x25, 0x64, 0xde, 0xf7, 0x7d, 0x6f, 0xbe,
	0xf7, 0xde, 0xbe, 0x81, 0xb7, 0x23, 0xcc, 0x50, 0x80, 0x2c, 0x72, 0x68, 0x45, 0x1b, 0x96, 0x38,
	0x36, 0x43, 0x46, 0x05, 0x55, 0x16, 0x92, 0xb0, 0x49, 0x0e, 0xcd, 0x68, 0x43, 0xbb, 0x85, 0x7c,
	0x2f, 0xa0, 0x56, 0xfc, 0x9b, 0x10, 0xb4, 0x25, 0x87, 0x72, 0x9f, 0x72, 0xcb, 0xe7, 0x44, 0x0a,
	0x7d, 0x4e, 0x52, 0x60, 0x39, 0x01, 0xaa, 0xf1, 0xc9, 0x4a, 0x0e, 0x29, 0xb4, 0x48, 0x28, 0xa1,
	0x49, 0x5c, 0xfe, 0xeb, 0x08, 0xfa, 0x1c, 0x84, 0x88, 0x21, 0x3f, 0x15, 0x14, 0xbe, 0x02, 0x78,
	0xb3, 0xc2, 0xc9, 0x7e, 0xe8, 0x22, 0x81, 0x5f, 0xc5, 0x88, 0xf2, 0x04, 0xce, 0xa3, 0xba, 0x38,
	0xa2, 0xcc, 0x13, 0x27, 0x2a, 0xc8, 0x03, 0x63, 0xbe, 0xac, 0x7e, 0xff, 0xb6, 0xbe, 0x98, 0xde,
	0x54, 0x72, 0x5d, 0x86, 0x39, 0xdf, 0x13, 0xcc, 0x0b, 0x88, 0x7d, 0x49, 0x55, 0xb6, 0x61, 0x36,
	0xc9, 0xad, 0x4e, 0xe5, 0x81, 0x91, 0xdb, 0x5c, 0x34, 0x7b, 0x4b, 0x34, 0x93, 0xec, 0xe5, 0xf9,
	0xf3, 0x9f, 0xf7, 0x32, 0x67, 0xed, 0xc6, 0x2a, 0xb0, 0x53, 0x7a, 0xd1, 0xfc, 0xd8, 0x6e, 0xac,
	0x5e, 0x26, 0x3a, 0x6d, 0x37, 0x56, 0xef, 0xa4, 0x96, 0x8f, 0xa5, 0xe9, 0x01, 0x83, 0x85, 0x65,
	0xb8, 0x34, 0x10, 0xb2, 0x31, 0x0f, 0x69, 0xc0, 0x71, 0xe1, 0xf7, 0x14, 0x5c, 0xa9, 0x70, 0x52,
	0x72, 0xdd, 0x17, 0x34, 0xc2, 0x2c, 0x40, 0x81, 0x83, 0x9f, 0x33, 0xe4, 0xe3, 0xf7, 0x94, 0xbd,
	0xdb, 0xa1, 0x4e, 0xdd, 0xc7, 0x81, 0x50, 0x8a, 0x30, 0xe7, 0x50, 0x16, 0x52, 0x86, 0x84, 0x47,
	0x83, 0xb1, 0x35, 0xf6, 0x92, 0x95, 0x47, 0xf0, 0x1a, 0x0d, 0x31, 0x43, 0x82, 0xb2, 0xb8, 0xce,
	0x51, 0xc2, 0x2e, 0x53, 0x59, 0x81, 0x0b, 0xd8, 0xa1, 0xfc, 0x84, 0x0b, 0xec, 0x57, 0x3d, 0x57,
	0x9d, 0xce, 0x03, 0x63, 0xc6, 0xce, 0x75, 0x63, 0xbb, 0xae, 0xa4, 0xb8, 0xd4, 0xa9, 0xd6, 0x50,
	0x40, 0xea, 0x88, 0x60, 0x75, 0x46, 0x26, 0xb7, 0x73, 0x2e, 0x75, 0x5e, 0xa6, 0x21, 0x65, 0x09,
	0xce, 0x49, 0x4a, 0x9d, 0xd5, 0xd4, 0xd9, 0x18, 0xcd, 0xba, 0xd4, 0xd9, 0x67, 0x35, 0xe5, 0x3e,
	0xbc, 0x21, 0x01, 0xd7, 0x23, 0x98, 0x8b, 0x2a, 0x67, 0x9e, 0x9a, 0x8d, 0x71, 0x99, 0x71, 0x27,
	0x0e, 0xee, 0x31, 0x4f, 0x51, 0xe1, 0x5c, 0x84, 0x19, 0x97, 0x25, 0xcf, 0xe5, 0x81, 0x71, 0xdd,
	0xee, 0x1c, 0x8b, 0xcf, 0xe4, 0x04, 0xba, 0x6e, 0xe5, 0x00, 0xd6, 0x07, 0x06, 0x30, 0xba, 0xa3,
	0x85, 0x35, 0xf8, 0x70, 0x2c, 0xa9, 0x3b, 0xa4, 0x4f, 0x53, 0x70, 0xad, 0xc2, 0xc9, 0x6e, 0xe0,
	0x30, 0x8c, 0x38, 0x2e, 0x39, 0xc2, 0x8b, 0xf0, 0x5f, 0x84, 0x6f, 0x12, 0x77, 0xff, 0xe5, 0xb8,
	0x8a, 0xbb, 0x43, 0x2d, 0xdb, 0x1e, 0x68, 0xd9, 0xa4, 0xf5, 0x15, 0x1e, 0xc3, 0xad, 0x2b, 0xd0,
	0x3b, 0x6d, 0xdc, 0xfc, 0x32, 0x0d, 0xa7, 0x2b, 0x9c, 0x28, 0xaf, 0xe1, 0x42, 0xdf, 0xfe, 0xde,
	0xed, 0xdf, 0xbb, 0x81, 0x55, 0xd1, 0x1e, 0x8c, 0x84, 0x3b, 0xd9, 0x95, 0x53, 0x00, 0xf5, 0x31,
	0x6b, 0x64, 0x0d, 0x65, 0x1a, 0x2d, 0xd0, 0xb6, 0xaf, 0x28, 0xe8, 0x9a, 0x39, 0x03, 0xd0, 0x98,
	0xf8, 0x73, 0x79, 0x3a, 0x74, 0xcb, 0xa4, 0x52, 0xad, 0xf4, 0xcf, 0xd2, 0x8e, 0x55, 0x6d, 0xf6,
	0x83, 0x7c, 0xdb, 0xca, 0xe5, 0xf3, 0xa6, 0x0e, 0x2e, 0x9a, 0x3a, 0xf8, 0xd5, 0xd4, 0xc1, 0xe7,
	0x96, 0x9e, 0xb9, 0x68, 0xe9, 0x99, 0x1f, 0x2d, 0x3d, 0xf3, 0xd6, 0x20, 0x9e, 0x38, 0xaa, 0x1f,
	0x98, 0x0e, 0xf5, 0xad, 0xe4, 0xb6, 0xf5, 0x1a, 0x3a, 0xe0, 0x56, 0xef, 0xd7, 0x23, 0x4e, 0x42,
	0xcc, 0x0f, 0xb2, 0xf1, 0x1b, 0xbd, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x2b, 0x0e, 0x99,
	0x42, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// [MOD-GF-MSG-1] Add Governance Framework Document
	AddGovernanceFrameworkDocument(ctx context.Context, in *MsgAddGovernanceFrameworkDocument, opts ...grpc.CallOption) (*MsgAddGovernanceFrameworkDocumentResponse, error)
	// [MOD-GF-MSG-2] Increase Active Governance Framework Version
	IncreaseActiveGovernanceFrameworkVersion(ctx context.Context, in *MsgIncreaseActiveGovernanceFrameworkVersion, opts ...grpc.CallOption) (*MsgIncreaseActiveGovernanceFrameworkVersionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/verana.gf.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddGovernanceFrameworkDocument(ctx context.Context, in *MsgAddGovernanceFrameworkDocument, opts ...grpc.CallOption) (*MsgAddGovernanceFrameworkDocumentResponse, error) {
	out := new(MsgAddGovernanceFrameworkDocumentResponse)
	err := c.cc.Invoke(ctx, "/verana.gf.v1.Msg/AddGovernanceFrameworkDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IncreaseActiveGovernanceFrameworkVersion(ctx context.Context, in *MsgIncreaseActiveGovernanceFrameworkVersion, opts ...grpc.CallOption) (*MsgIncreaseActiveGovernanceFrameworkVersionResponse, error) {
	out := new(MsgIncreaseActiveGovernanceFrameworkVersionResponse)
	err := c.cc.Invoke(ctx, "/verana.gf.v1.Msg/IncreaseActiveGovernanceFrameworkVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// [MOD-GF-MSG-1] Add Governance Framework Document
	AddGovernanceFrameworkDocument(context.Context, *MsgAddGovernanceFrameworkDocument) (*MsgAddGovernanceFrameworkDocumentResponse, error)
	// [MOD-GF-MSG-2] Increase Active Governance Framework Version
	IncreaseActiveGovernanceFrameworkVersion(context.Context, *MsgIncreaseActiveGovernanceFrameworkVersion) (*MsgIncreaseActiveGovernanceFrameworkVersionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) AddGovernanceFrameworkDocument(ctx context.Context, req *MsgAddGovernanceFrameworkDocument) (*MsgAddGovernanceFrameworkDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGovernanceFrameworkDocument not implemented")
}
func (*UnimplementedMsgServer) IncreaseActiveGovernanceFrameworkVersion(ctx context.Context, req *MsgIncreaseActiveGovernanceFrameworkVersion) (*MsgIncreaseActiveGovernanceFrameworkVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseActiveGovernanceFrameworkVersion not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.gf.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddGovernanceFrameworkDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddGovernanceFrameworkDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddGovernanceFrameworkDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.gf.v1.Msg/AddGovernanceFrameworkDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddGovernanceFrameworkDocument(ctx, req.(*MsgAddGovernanceFrameworkDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IncreaseActiveGovernanceFrameworkVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIncreaseActiveGovernanceFrameworkVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IncreaseActiveGovernanceFrameworkVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.gf.v1.Msg/IncreaseActiveGovernanceFrameworkVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IncreaseActiveGovernanceFrameworkVersion(ctx, req.(*MsgIncreaseActiveGovernanceFrameworkVersion))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verana.gf.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "AddGovernanceFrameworkDocument",
			Handler:    _Msg_AddGovernanceFrameworkDocument_Handler,
		},
		{
			MethodName: "IncreaseActiveGovernanceFrameworkVersion",
			Handler:    _Msg_IncreaseActiveGovernanceFrameworkVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verana/gf/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddGovernanceFrameworkDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddGovernanceFrameworkDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddGovernanceFrameworkDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Version != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Version))
		i--
		dAtA[i] = 0x38
	}
	if len(m.DocDigestSri) > 0 {
		i -= len(m.DocDigestSri)
		copy(dAtA[i:], m.DocDigestSri)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocDigestSri)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DocUrl) > 0 {
		i -= len(m.DocUrl)
		copy(dAtA[i:], m.DocUrl)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocUrl)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.DocLanguage) > 0 {
		i -= len(m.DocLanguage)
		copy(dAtA[i:], m.DocLanguage)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocLanguage)))
		i--
		dAtA[i] = 0x22
	}
	if m.EcosystemId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EcosystemId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Corporation) > 0 {
		i -= len(m.Corporation)
		copy(dAtA[i:], m.Corporation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Corporation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddGovernanceFrameworkDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddGovernanceFrameworkDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddGovernanceFrameworkDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EcosystemId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EcosystemId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Corporation) > 0 {
		i -= len(m.Corporation)
		copy(dAtA[i:], m.Corporation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Corporation)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddGovernanceFrameworkDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Corporation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EcosystemId != 0 {
		n += 1 + sovTx(uint64(m.EcosystemId))
	}
	l = len(m.DocLanguage)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocUrl)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocDigestSri)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Version != 0 {
		n += 1 + sovTx(uint64(m.Version))
	}
	return n
}

func (m *MsgAddGovernanceFrameworkDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Corporation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EcosystemId != 0 {
		n += 1 + sovTx(uint64(m.EcosystemId))
	}
	return n
}

func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddGovernanceFrameworkDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddGovernanceFrameworkDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddGovernanceFrameworkDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corporation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Corporation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcosystemId", wireType)
			}
			m.EcosystemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EcosystemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocLanguage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocLanguage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocDigestSri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocDigestSri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			m.Version = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Version |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddGovernanceFrameworkDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddGovernanceFrameworkDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddGovernanceFrameworkDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIncreaseActiveGovernanceFrameworkVersion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIncreaseActiveGovernanceFrameworkVersion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Corporation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Corporation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcosystemId", wireType)
			}
			m.EcosystemId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EcosystemId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIncreaseActiveGovernanceFrameworkVersionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIncreaseActiveGovernanceFrameworkVersionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIncreaseActiveGovernanceFrameworkVersionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
