// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/co/v1/tx.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Any } from "../../../google/protobuf/any";
import { Params } from "./params";
import Long = require("long");

export const protobufPackage = "verana.co.v1";

/**
 * Member is the MOD-CO-local mirror of cosmos.group.v1.MemberRequest. We don't
 * import the x/group proto directly because the buf cosmos-sdk dep pinned by
 * this repo predates the x/group proto export. The Go keeper converts this
 * type to the cosmos.group.v1.MemberRequest before calling x/group.
 */
export interface Member {
  /** address is the bech32 address of the member. */
  address: string;
  /**
   * weight is the member's voting weight. MUST be a non-zero decimal string
   * representing a positive number (e.g. "1", "10").
   */
  weight: string;
  /** metadata is optional arbitrary metadata attached to the member. */
  metadata: string;
}

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  authority: string;
  params: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

/**
 * MsgCreateCorporation — MOD-CO-MSG-1.
 *
 * Signer is the submitting account; no privilege required. Forwarded as the
 * `admin` field of the underlying `MsgCreateGroupWithPolicy`. After execution,
 * the signer holds no ongoing admin privileges over the group, group policy,
 * or Corporation — the group_policy_address becomes the admin of both the
 * group and the group policy (`group_policy_as_admin` is hardcoded to `true`).
 */
export interface MsgCreateCorporation {
  signer: string;
  /** members is the initial group membership list. MUST contain at least one. */
  members: Member[];
  groupMetadata: string;
  groupPolicyMetadata: string;
  /**
   * decision_policy must encode a cosmos.group.v1.ThresholdDecisionPolicy or
   * cosmos.group.v1.PercentageDecisionPolicy. Passed through to x/group.
   */
  decisionPolicy:
    | Any
    | undefined;
  /** did is the DID of the new Corporation. MUST be globally unique. */
  did: string;
  /** language is the primary language tag (BCP 47). */
  language: string;
  /** doc_url is the URL of the v1 CGF document. */
  docUrl: string;
  /** doc_digest_sri is the digest_sri of the v1 CGF document. */
  docDigestSri: string;
}

export interface MsgCreateCorporationResponse {
  corporationId: number;
  policyAddress: string;
}

/**
 * MsgUpdateCorporation — MOD-CO-MSG-2. Rotates the DID of an existing
 * Corporation. `language` is immutable and cannot be updated.
 */
export interface MsgUpdateCorporation {
  corporation: string;
  operator: string;
  did: string;
}

export interface MsgUpdateCorporationResponse {
}

function createBaseMember(): Member {
  return { address: "", weight: "", metadata: "" };
}

export const Member = {
  encode(message: Member, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    if (message.weight !== "") {
      writer.uint32(18).string(message.weight);
    }
    if (message.metadata !== "") {
      writer.uint32(26).string(message.metadata);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Member {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.weight = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.metadata = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Member {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      weight: isSet(object.weight) ? globalThis.String(object.weight) : "",
      metadata: isSet(object.metadata) ? globalThis.String(object.metadata) : "",
    };
  },

  toJSON(message: Member): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.weight !== "") {
      obj.weight = message.weight;
    }
    if (message.metadata !== "") {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Member>, I>>(base?: I): Member {
    return Member.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Member>, I>>(object: I): Member {
    const message = createBaseMember();
    message.address = object.address ?? "";
    message.weight = object.weight ?? "";
    message.metadata = object.metadata ?? "";
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams = {
  encode(message: MsgUpdateParams, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse = {
  encode(_: MsgUpdateParamsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgCreateCorporation(): MsgCreateCorporation {
  return {
    signer: "",
    members: [],
    groupMetadata: "",
    groupPolicyMetadata: "",
    decisionPolicy: undefined,
    did: "",
    language: "",
    docUrl: "",
    docDigestSri: "",
  };
}

export const MsgCreateCorporation = {
  encode(message: MsgCreateCorporation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    for (const v of message.members) {
      Member.encode(v!, writer.uint32(18).fork()).ldelim();
    }
    if (message.groupMetadata !== "") {
      writer.uint32(26).string(message.groupMetadata);
    }
    if (message.groupPolicyMetadata !== "") {
      writer.uint32(34).string(message.groupPolicyMetadata);
    }
    if (message.decisionPolicy !== undefined) {
      Any.encode(message.decisionPolicy, writer.uint32(42).fork()).ldelim();
    }
    if (message.did !== "") {
      writer.uint32(50).string(message.did);
    }
    if (message.language !== "") {
      writer.uint32(58).string(message.language);
    }
    if (message.docUrl !== "") {
      writer.uint32(66).string(message.docUrl);
    }
    if (message.docDigestSri !== "") {
      writer.uint32(74).string(message.docDigestSri);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgCreateCorporation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateCorporation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.members.push(Member.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.groupMetadata = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.groupPolicyMetadata = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.decisionPolicy = Any.decode(reader, reader.uint32());
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.did = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.language = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.docUrl = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.docDigestSri = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateCorporation {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      members: globalThis.Array.isArray(object?.members) ? object.members.map((e: any) => Member.fromJSON(e)) : [],
      groupMetadata: isSet(object.groupMetadata) ? globalThis.String(object.groupMetadata) : "",
      groupPolicyMetadata: isSet(object.groupPolicyMetadata) ? globalThis.String(object.groupPolicyMetadata) : "",
      decisionPolicy: isSet(object.decisionPolicy) ? Any.fromJSON(object.decisionPolicy) : undefined,
      did: isSet(object.did) ? globalThis.String(object.did) : "",
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      docUrl: isSet(object.docUrl) ? globalThis.String(object.docUrl) : "",
      docDigestSri: isSet(object.docDigestSri) ? globalThis.String(object.docDigestSri) : "",
    };
  },

  toJSON(message: MsgCreateCorporation): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.members?.length) {
      obj.members = message.members.map((e) => Member.toJSON(e));
    }
    if (message.groupMetadata !== "") {
      obj.groupMetadata = message.groupMetadata;
    }
    if (message.groupPolicyMetadata !== "") {
      obj.groupPolicyMetadata = message.groupPolicyMetadata;
    }
    if (message.decisionPolicy !== undefined) {
      obj.decisionPolicy = Any.toJSON(message.decisionPolicy);
    }
    if (message.did !== "") {
      obj.did = message.did;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.docUrl !== "") {
      obj.docUrl = message.docUrl;
    }
    if (message.docDigestSri !== "") {
      obj.docDigestSri = message.docDigestSri;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateCorporation>, I>>(base?: I): MsgCreateCorporation {
    return MsgCreateCorporation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateCorporation>, I>>(object: I): MsgCreateCorporation {
    const message = createBaseMsgCreateCorporation();
    message.signer = object.signer ?? "";
    message.members = object.members?.map((e) => Member.fromPartial(e)) || [];
    message.groupMetadata = object.groupMetadata ?? "";
    message.groupPolicyMetadata = object.groupPolicyMetadata ?? "";
    message.decisionPolicy = (object.decisionPolicy !== undefined && object.decisionPolicy !== null)
      ? Any.fromPartial(object.decisionPolicy)
      : undefined;
    message.did = object.did ?? "";
    message.language = object.language ?? "";
    message.docUrl = object.docUrl ?? "";
    message.docDigestSri = object.docDigestSri ?? "";
    return message;
  },
};

function createBaseMsgCreateCorporationResponse(): MsgCreateCorporationResponse {
  return { corporationId: 0, policyAddress: "" };
}

export const MsgCreateCorporationResponse = {
  encode(message: MsgCreateCorporationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.corporationId !== 0) {
      writer.uint32(8).uint64(message.corporationId);
    }
    if (message.policyAddress !== "") {
      writer.uint32(18).string(message.policyAddress);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgCreateCorporationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateCorporationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.corporationId = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.policyAddress = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateCorporationResponse {
    return {
      corporationId: isSet(object.corporationId) ? globalThis.Number(object.corporationId) : 0,
      policyAddress: isSet(object.policyAddress) ? globalThis.String(object.policyAddress) : "",
    };
  },

  toJSON(message: MsgCreateCorporationResponse): unknown {
    const obj: any = {};
    if (message.corporationId !== 0) {
      obj.corporationId = Math.round(message.corporationId);
    }
    if (message.policyAddress !== "") {
      obj.policyAddress = message.policyAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCreateCorporationResponse>, I>>(base?: I): MsgCreateCorporationResponse {
    return MsgCreateCorporationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCreateCorporationResponse>, I>>(object: I): MsgCreateCorporationResponse {
    const message = createBaseMsgCreateCorporationResponse();
    message.corporationId = object.corporationId ?? 0;
    message.policyAddress = object.policyAddress ?? "";
    return message;
  },
};

function createBaseMsgUpdateCorporation(): MsgUpdateCorporation {
  return { corporation: "", operator: "", did: "" };
}

export const MsgUpdateCorporation = {
  encode(message: MsgUpdateCorporation, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.corporation !== "") {
      writer.uint32(10).string(message.corporation);
    }
    if (message.operator !== "") {
      writer.uint32(18).string(message.operator);
    }
    if (message.did !== "") {
      writer.uint32(26).string(message.did);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdateCorporation {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateCorporation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.corporation = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.operator = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.did = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateCorporation {
    return {
      corporation: isSet(object.corporation) ? globalThis.String(object.corporation) : "",
      operator: isSet(object.operator) ? globalThis.String(object.operator) : "",
      did: isSet(object.did) ? globalThis.String(object.did) : "",
    };
  },

  toJSON(message: MsgUpdateCorporation): unknown {
    const obj: any = {};
    if (message.corporation !== "") {
      obj.corporation = message.corporation;
    }
    if (message.operator !== "") {
      obj.operator = message.operator;
    }
    if (message.did !== "") {
      obj.did = message.did;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateCorporation>, I>>(base?: I): MsgUpdateCorporation {
    return MsgUpdateCorporation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateCorporation>, I>>(object: I): MsgUpdateCorporation {
    const message = createBaseMsgUpdateCorporation();
    message.corporation = object.corporation ?? "";
    message.operator = object.operator ?? "";
    message.did = object.did ?? "";
    return message;
  },
};

function createBaseMsgUpdateCorporationResponse(): MsgUpdateCorporationResponse {
  return {};
}

export const MsgUpdateCorporationResponse = {
  encode(_: MsgUpdateCorporationResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgUpdateCorporationResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateCorporationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateCorporationResponse {
    return {};
  },

  toJSON(_: MsgUpdateCorporationResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateCorporationResponse>, I>>(base?: I): MsgUpdateCorporationResponse {
    return MsgUpdateCorporationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateCorporationResponse>, I>>(_: I): MsgUpdateCorporationResponse {
    const message = createBaseMsgUpdateCorporationResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /**
   * [MOD-CO-MSG-1] Create New Corporation — atomically create an x/group
   * group + group policy and register the resulting policy_address as a new
   * Corporation VPR entry.
   */
  CreateCorporation(request: MsgCreateCorporation): Promise<MsgCreateCorporationResponse>;
  /**
   * [MOD-CO-MSG-2] Update Corporation — rotate the DID of an existing
   * Corporation. Signers: corporation (policy_address) + operator.
   */
  UpdateCorporation(request: MsgUpdateCorporation): Promise<MsgUpdateCorporationResponse>;
}

export const MsgServiceName = "verana.co.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.CreateCorporation = this.CreateCorporation.bind(this);
    this.UpdateCorporation = this.UpdateCorporation.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(_m0.Reader.create(data)));
  }

  CreateCorporation(request: MsgCreateCorporation): Promise<MsgCreateCorporationResponse> {
    const data = MsgCreateCorporation.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateCorporation", data);
    return promise.then((data) => MsgCreateCorporationResponse.decode(_m0.Reader.create(data)));
  }

  UpdateCorporation(request: MsgUpdateCorporation): Promise<MsgUpdateCorporationResponse> {
    const data = MsgUpdateCorporation.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateCorporation", data);
    return promise.then((data) => MsgUpdateCorporationResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
