// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/ec/v1/query.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { Params } from "./params";
import { EcosystemWithVersions } from "./types";
import Long = require("long");

export const protobufPackage = "verana.ec.v1";

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params: Params | undefined;
}

export interface QueryGetEcosystemRequest {
  id: number;
  activeGfOnly: boolean;
  preferredLanguage: string;
}

export interface QueryGetEcosystemResponse {
  ecosystem: EcosystemWithVersions | undefined;
}

export interface QueryListEcosystemsRequest {
  corporationId: number;
  modifiedAfter: Date | undefined;
  activeGfOnly: boolean;
  preferredLanguage: string;
  responseMaxSize: number;
}

export interface QueryListEcosystemsResponse {
  ecosystems: EcosystemWithVersions[];
}

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest = {
  encode(_: QueryParamsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse = {
  encode(message: QueryParamsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryGetEcosystemRequest(): QueryGetEcosystemRequest {
  return { id: 0, activeGfOnly: false, preferredLanguage: "" };
}

export const QueryGetEcosystemRequest = {
  encode(message: QueryGetEcosystemRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.activeGfOnly !== false) {
      writer.uint32(16).bool(message.activeGfOnly);
    }
    if (message.preferredLanguage !== "") {
      writer.uint32(26).string(message.preferredLanguage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryGetEcosystemRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEcosystemRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.activeGfOnly = reader.bool();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.preferredLanguage = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEcosystemRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      activeGfOnly: isSet(object.activeGfOnly) ? globalThis.Boolean(object.activeGfOnly) : false,
      preferredLanguage: isSet(object.preferredLanguage) ? globalThis.String(object.preferredLanguage) : "",
    };
  },

  toJSON(message: QueryGetEcosystemRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.activeGfOnly !== false) {
      obj.activeGfOnly = message.activeGfOnly;
    }
    if (message.preferredLanguage !== "") {
      obj.preferredLanguage = message.preferredLanguage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEcosystemRequest>, I>>(base?: I): QueryGetEcosystemRequest {
    return QueryGetEcosystemRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEcosystemRequest>, I>>(object: I): QueryGetEcosystemRequest {
    const message = createBaseQueryGetEcosystemRequest();
    message.id = object.id ?? 0;
    message.activeGfOnly = object.activeGfOnly ?? false;
    message.preferredLanguage = object.preferredLanguage ?? "";
    return message;
  },
};

function createBaseQueryGetEcosystemResponse(): QueryGetEcosystemResponse {
  return { ecosystem: undefined };
}

export const QueryGetEcosystemResponse = {
  encode(message: QueryGetEcosystemResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.ecosystem !== undefined) {
      EcosystemWithVersions.encode(message.ecosystem, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryGetEcosystemResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEcosystemResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ecosystem = EcosystemWithVersions.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEcosystemResponse {
    return { ecosystem: isSet(object.ecosystem) ? EcosystemWithVersions.fromJSON(object.ecosystem) : undefined };
  },

  toJSON(message: QueryGetEcosystemResponse): unknown {
    const obj: any = {};
    if (message.ecosystem !== undefined) {
      obj.ecosystem = EcosystemWithVersions.toJSON(message.ecosystem);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEcosystemResponse>, I>>(base?: I): QueryGetEcosystemResponse {
    return QueryGetEcosystemResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEcosystemResponse>, I>>(object: I): QueryGetEcosystemResponse {
    const message = createBaseQueryGetEcosystemResponse();
    message.ecosystem = (object.ecosystem !== undefined && object.ecosystem !== null)
      ? EcosystemWithVersions.fromPartial(object.ecosystem)
      : undefined;
    return message;
  },
};

function createBaseQueryListEcosystemsRequest(): QueryListEcosystemsRequest {
  return { corporationId: 0, modifiedAfter: undefined, activeGfOnly: false, preferredLanguage: "", responseMaxSize: 0 };
}

export const QueryListEcosystemsRequest = {
  encode(message: QueryListEcosystemsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.corporationId !== 0) {
      writer.uint32(8).uint64(message.corporationId);
    }
    if (message.modifiedAfter !== undefined) {
      Timestamp.encode(toTimestamp(message.modifiedAfter), writer.uint32(18).fork()).ldelim();
    }
    if (message.activeGfOnly !== false) {
      writer.uint32(24).bool(message.activeGfOnly);
    }
    if (message.preferredLanguage !== "") {
      writer.uint32(34).string(message.preferredLanguage);
    }
    if (message.responseMaxSize !== 0) {
      writer.uint32(40).uint32(message.responseMaxSize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryListEcosystemsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListEcosystemsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.corporationId = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.modifiedAfter = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.activeGfOnly = reader.bool();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.preferredLanguage = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.responseMaxSize = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListEcosystemsRequest {
    return {
      corporationId: isSet(object.corporationId) ? globalThis.Number(object.corporationId) : 0,
      modifiedAfter: isSet(object.modifiedAfter) ? fromJsonTimestamp(object.modifiedAfter) : undefined,
      activeGfOnly: isSet(object.activeGfOnly) ? globalThis.Boolean(object.activeGfOnly) : false,
      preferredLanguage: isSet(object.preferredLanguage) ? globalThis.String(object.preferredLanguage) : "",
      responseMaxSize: isSet(object.responseMaxSize) ? globalThis.Number(object.responseMaxSize) : 0,
    };
  },

  toJSON(message: QueryListEcosystemsRequest): unknown {
    const obj: any = {};
    if (message.corporationId !== 0) {
      obj.corporationId = Math.round(message.corporationId);
    }
    if (message.modifiedAfter !== undefined) {
      obj.modifiedAfter = message.modifiedAfter.toISOString();
    }
    if (message.activeGfOnly !== false) {
      obj.activeGfOnly = message.activeGfOnly;
    }
    if (message.preferredLanguage !== "") {
      obj.preferredLanguage = message.preferredLanguage;
    }
    if (message.responseMaxSize !== 0) {
      obj.responseMaxSize = Math.round(message.responseMaxSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListEcosystemsRequest>, I>>(base?: I): QueryListEcosystemsRequest {
    return QueryListEcosystemsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListEcosystemsRequest>, I>>(object: I): QueryListEcosystemsRequest {
    const message = createBaseQueryListEcosystemsRequest();
    message.corporationId = object.corporationId ?? 0;
    message.modifiedAfter = object.modifiedAfter ?? undefined;
    message.activeGfOnly = object.activeGfOnly ?? false;
    message.preferredLanguage = object.preferredLanguage ?? "";
    message.responseMaxSize = object.responseMaxSize ?? 0;
    return message;
  },
};

function createBaseQueryListEcosystemsResponse(): QueryListEcosystemsResponse {
  return { ecosystems: [] };
}

export const QueryListEcosystemsResponse = {
  encode(message: QueryListEcosystemsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.ecosystems) {
      EcosystemWithVersions.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): QueryListEcosystemsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListEcosystemsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.ecosystems.push(EcosystemWithVersions.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListEcosystemsResponse {
    return {
      ecosystems: globalThis.Array.isArray(object?.ecosystems)
        ? object.ecosystems.map((e: any) => EcosystemWithVersions.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryListEcosystemsResponse): unknown {
    const obj: any = {};
    if (message.ecosystems?.length) {
      obj.ecosystems = message.ecosystems.map((e) => EcosystemWithVersions.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListEcosystemsResponse>, I>>(base?: I): QueryListEcosystemsResponse {
    return QueryListEcosystemsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListEcosystemsResponse>, I>>(object: I): QueryListEcosystemsResponse {
    const message = createBaseQueryListEcosystemsResponse();
    message.ecosystems = object.ecosystems?.map((e) => EcosystemWithVersions.fromPartial(e)) || [];
    return message;
  },
};

/** Query defines the gRPC querier service. */
export interface Query {
  /** [MOD-ES-QRY-3] List Module Parameters. */
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse>;
  /** [MOD-ES-QRY-1] Get Ecosystem by id, with nested GF version + document data. */
  GetEcosystem(request: QueryGetEcosystemRequest): Promise<QueryGetEcosystemResponse>;
  /** [MOD-ES-QRY-2] List Ecosystems, optionally filtered. */
  ListEcosystems(request: QueryListEcosystemsRequest): Promise<QueryListEcosystemsResponse>;
}

export const QueryServiceName = "verana.ec.v1.Query";
export class QueryClientImpl implements Query {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QueryServiceName;
    this.rpc = rpc;
    this.Params = this.Params.bind(this);
    this.GetEcosystem = this.GetEcosystem.bind(this);
    this.ListEcosystems = this.ListEcosystems.bind(this);
  }
  Params(request: QueryParamsRequest): Promise<QueryParamsResponse> {
    const data = QueryParamsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Params", data);
    return promise.then((data) => QueryParamsResponse.decode(_m0.Reader.create(data)));
  }

  GetEcosystem(request: QueryGetEcosystemRequest): Promise<QueryGetEcosystemResponse> {
    const data = QueryGetEcosystemRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetEcosystem", data);
    return promise.then((data) => QueryGetEcosystemResponse.decode(_m0.Reader.create(data)));
  }

  ListEcosystems(request: QueryListEcosystemsRequest): Promise<QueryListEcosystemsResponse> {
    const data = QueryListEcosystemsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListEcosystems", data);
    return promise.then((data) => QueryListEcosystemsResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
