// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               unknown
// source: verana/ec/v1/types.proto

/* eslint-disable */
import * as _m0 from "protobufjs/minimal";
import { Timestamp } from "../../../google/protobuf/timestamp";
import { GovernanceFrameworkVersionWithDocs } from "../../gf/v1/types";
import Long = require("long");

export const protobufPackage = "verana.ec.v1";

/**
 * Ecosystem is the VPR-level entity introduced in spec v4-rc2 as the
 * replacement for the legacy Trust Registry concept. An Ecosystem is
 * identified by its uint64 `id` and controlled by the Corporation referenced
 * via `corporation_id`. Per-Ecosystem DID uniqueness is NOT enforced; the
 * `(did, corporation_id)` consistency invariant is enforced instead — see
 * MOD-ES-MSG-1-2-1 and MOD-ES-MSG-2-2-1.
 *
 * active_version is uint32 (spec literally says "int"); version numbers are
 * always >= 1 and this matches the MOD-GF version type.
 */
export interface Ecosystem {
  id: number;
  did: string;
  corporationId: number;
  created: Date | undefined;
  modified: Date | undefined;
  archived: boolean;
  language: string;
  activeVersion: number;
}

/**
 * EcosystemWithVersions is the query response shape (MOD-ES-QRY-1 /
 * MOD-ES-QRY-2) including nested governance framework versions and documents
 * pulled from the x/gf module.
 */
export interface EcosystemWithVersions {
  id: number;
  did: string;
  corporationId: number;
  created: Date | undefined;
  modified: Date | undefined;
  archived: boolean;
  language: string;
  activeVersion: number;
  versions: GovernanceFrameworkVersionWithDocs[];
}

function createBaseEcosystem(): Ecosystem {
  return {
    id: 0,
    did: "",
    corporationId: 0,
    created: undefined,
    modified: undefined,
    archived: false,
    language: "",
    activeVersion: 0,
  };
}

export const Ecosystem = {
  encode(message: Ecosystem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.did !== "") {
      writer.uint32(18).string(message.did);
    }
    if (message.corporationId !== 0) {
      writer.uint32(24).uint64(message.corporationId);
    }
    if (message.created !== undefined) {
      Timestamp.encode(toTimestamp(message.created), writer.uint32(34).fork()).ldelim();
    }
    if (message.modified !== undefined) {
      Timestamp.encode(toTimestamp(message.modified), writer.uint32(42).fork()).ldelim();
    }
    if (message.archived !== false) {
      writer.uint32(48).bool(message.archived);
    }
    if (message.language !== "") {
      writer.uint32(58).string(message.language);
    }
    if (message.activeVersion !== 0) {
      writer.uint32(64).uint32(message.activeVersion);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Ecosystem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEcosystem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.did = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.corporationId = longToNumber(reader.uint64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.created = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.modified = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.archived = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.language = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.activeVersion = reader.uint32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Ecosystem {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      did: isSet(object.did) ? globalThis.String(object.did) : "",
      corporationId: isSet(object.corporationId) ? globalThis.Number(object.corporationId) : 0,
      created: isSet(object.created) ? fromJsonTimestamp(object.created) : undefined,
      modified: isSet(object.modified) ? fromJsonTimestamp(object.modified) : undefined,
      archived: isSet(object.archived) ? globalThis.Boolean(object.archived) : false,
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      activeVersion: isSet(object.activeVersion) ? globalThis.Number(object.activeVersion) : 0,
    };
  },

  toJSON(message: Ecosystem): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.did !== "") {
      obj.did = message.did;
    }
    if (message.corporationId !== 0) {
      obj.corporationId = Math.round(message.corporationId);
    }
    if (message.created !== undefined) {
      obj.created = message.created.toISOString();
    }
    if (message.modified !== undefined) {
      obj.modified = message.modified.toISOString();
    }
    if (message.archived !== false) {
      obj.archived = message.archived;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.activeVersion !== 0) {
      obj.activeVersion = Math.round(message.activeVersion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Ecosystem>, I>>(base?: I): Ecosystem {
    return Ecosystem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Ecosystem>, I>>(object: I): Ecosystem {
    const message = createBaseEcosystem();
    message.id = object.id ?? 0;
    message.did = object.did ?? "";
    message.corporationId = object.corporationId ?? 0;
    message.created = object.created ?? undefined;
    message.modified = object.modified ?? undefined;
    message.archived = object.archived ?? false;
    message.language = object.language ?? "";
    message.activeVersion = object.activeVersion ?? 0;
    return message;
  },
};

function createBaseEcosystemWithVersions(): EcosystemWithVersions {
  return {
    id: 0,
    did: "",
    corporationId: 0,
    created: undefined,
    modified: undefined,
    archived: false,
    language: "",
    activeVersion: 0,
    versions: [],
  };
}

export const EcosystemWithVersions = {
  encode(message: EcosystemWithVersions, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).uint64(message.id);
    }
    if (message.did !== "") {
      writer.uint32(18).string(message.did);
    }
    if (message.corporationId !== 0) {
      writer.uint32(24).uint64(message.corporationId);
    }
    if (message.created !== undefined) {
      Timestamp.encode(toTimestamp(message.created), writer.uint32(34).fork()).ldelim();
    }
    if (message.modified !== undefined) {
      Timestamp.encode(toTimestamp(message.modified), writer.uint32(42).fork()).ldelim();
    }
    if (message.archived !== false) {
      writer.uint32(48).bool(message.archived);
    }
    if (message.language !== "") {
      writer.uint32(58).string(message.language);
    }
    if (message.activeVersion !== 0) {
      writer.uint32(64).uint32(message.activeVersion);
    }
    for (const v of message.versions) {
      GovernanceFrameworkVersionWithDocs.encode(v!, writer.uint32(74).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): EcosystemWithVersions {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEcosystemWithVersions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.did = reader.string();
          continue;
        case 3:
          if (tag !== 24) {
            break;
          }

          message.corporationId = longToNumber(reader.uint64() as Long);
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.created = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.modified = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.archived = reader.bool();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.language = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.activeVersion = reader.uint32();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.versions.push(GovernanceFrameworkVersionWithDocs.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EcosystemWithVersions {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      did: isSet(object.did) ? globalThis.String(object.did) : "",
      corporationId: isSet(object.corporationId) ? globalThis.Number(object.corporationId) : 0,
      created: isSet(object.created) ? fromJsonTimestamp(object.created) : undefined,
      modified: isSet(object.modified) ? fromJsonTimestamp(object.modified) : undefined,
      archived: isSet(object.archived) ? globalThis.Boolean(object.archived) : false,
      language: isSet(object.language) ? globalThis.String(object.language) : "",
      activeVersion: isSet(object.activeVersion) ? globalThis.Number(object.activeVersion) : 0,
      versions: globalThis.Array.isArray(object?.versions)
        ? object.versions.map((e: any) => GovernanceFrameworkVersionWithDocs.fromJSON(e))
        : [],
    };
  },

  toJSON(message: EcosystemWithVersions): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.did !== "") {
      obj.did = message.did;
    }
    if (message.corporationId !== 0) {
      obj.corporationId = Math.round(message.corporationId);
    }
    if (message.created !== undefined) {
      obj.created = message.created.toISOString();
    }
    if (message.modified !== undefined) {
      obj.modified = message.modified.toISOString();
    }
    if (message.archived !== false) {
      obj.archived = message.archived;
    }
    if (message.language !== "") {
      obj.language = message.language;
    }
    if (message.activeVersion !== 0) {
      obj.activeVersion = Math.round(message.activeVersion);
    }
    if (message.versions?.length) {
      obj.versions = message.versions.map((e) => GovernanceFrameworkVersionWithDocs.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EcosystemWithVersions>, I>>(base?: I): EcosystemWithVersions {
    return EcosystemWithVersions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EcosystemWithVersions>, I>>(object: I): EcosystemWithVersions {
    const message = createBaseEcosystemWithVersions();
    message.id = object.id ?? 0;
    message.did = object.did ?? "";
    message.corporationId = object.corporationId ?? 0;
    message.created = object.created ?? undefined;
    message.modified = object.modified ?? undefined;
    message.archived = object.archived ?? false;
    message.language = object.language ?? "";
    message.activeVersion = object.activeVersion ?? 0;
    message.versions = object.versions?.map((e) => GovernanceFrameworkVersionWithDocs.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(long: Long): number {
  if (long.gt(globalThis.Number.MAX_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (long.lt(globalThis.Number.MIN_SAFE_INTEGER)) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return long.toNumber();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
